### PR TITLE
Add instructions for installing gcc-13 on Ubuntu 22.04

### PR DESCRIPTION
**Pull request by curiousercreative**

### CODE REVIEW

**Comment by alexanderbock** [comment]
Hi! Would be curious to hear about the issues that you've had with building a second time.   It shouldn't be necessary to nuke the build folder

**Comment by alexanderbock** [comment]
Just tested in the docker image (https://github.com/OpenSpace/docker/blob/master/build/ubuntu-2204-gcc13.Dockerfile) and it works for me to build twice:
  1. `git clone --recursive --jobs 8 --depth 1 https://github.com/OpenSpace/OpenSpace`
  2. `cd OpenSpace`
  3. `mkdir build`
  4. `cmake -S . -B ./build`
  5. `cmake --build build --parallel 24`
  6. ...
  7. `cmake --build build --parallel 24` again


```
root@b384e20c7345:/OpenSpace# cmake --build build --parallel 24
[  0%] Built target websocketpp-configure
[  0%] Built target TracyClient
[  0%] Built target lz4
[  0%] Built target simdutf
[  0%] Built target stb_image
[  1%] Built target zlibstatic
[  1%] Built target codegen-lib
[  1%] Built target tiny-process-library
[  2%] Built target Lua
[  2%] Built target ryu
[  2%] Built target Imgui
[  3%] Built target freetype
[  3%] Built target tinyxml2
[  4%] Built target soloud
[  4%] Built target glad
[  6%] Built target cfitsio
[  6%] Built target nlohmann_json_schema_validator
[  6%] Built target zlib1
[  6%] Built target websocketpp-build
[  6%] Built target codegen
[  8%] Built target glbinding
[ 11%] Built target libcef_dll_wrapper
[ 12%] Built target glfw
[ 12%] Generating __codegen_unittest.h
codegen /OpenSpace/support/coding/codegen/tests/execution_enums /OpenSpace/support/coding/codegen/tests/execution_luawrapper /OpenSpace/support/coding/codegen/tests/execution_misc /OpenSpace/support/coding/codegen/tests/execution_structs
[ 12%] Built target scn
[ 13%] Built target minizip
[ 13%] Generating __codegen.h
codegen modules src
[ 14%] Built target png
[ 14%] Built target CCfits
[ 14%] Built target websocketpp
0/0 files changed in 13.696444 ms.  Pure time in codegen: 0 ms
[ 14%] Built target run_test_codegen
[ 14%] Built target OpenSpace_Helper
[ 14%] Built target glbinding-aux
[ 16%] Built target Catch2
[ 16%] Built target Catch2WithMain
0/322 files changed in 28.659409 ms.  Pure time in codegen: 0 ms
[ 16%] Built target run_codegen
[ 17%] Built target sgct
[ 22%] Built target assimp
[ 22%] Built target SGCTTest
[ 25%] Built target Ghoul
[ 25%] Built target GhoulTest
[ 75%] Built target spice
[ 78%] Built target openspace-core
[ 78%] Built target openspace-module-fitsfilereader
[ 78%] Built target openspace-module-audio
[ 78%] Built target openspace-module-debugging
[ 78%] Built target openspace-module-atmosphere
[ 78%] Built target openspace-module-digitaluniverse
[ 79%] Built target openspace-module-webbrowser
[ 79%] Built target openspace-module-webgui
[ 80%] Built target openspace-module-statemachine
[ 80%] Built target openspace-module-sync
[ 80%] Built target openspace-module-galaxy
[ 80%] Built target openspace-module-vislab
[ 81%] Built target openspace-module-imgui
[ 81%] Built target openspace-module-spacecraftinstruments
[ 81%] Built target openspace-module-toyvolume
[ 83%] Built target openspace-module-base
[ 83%] Built target openspace-module-cefwebgui
[ 83%] Built target openspace-module-volume
[ 83%] Built target openspace-module-gaia
[ 84%] Built target openspace-module-skybrowser
[ 84%] Built target openspace-module-space
[ 92%] Built target geos
[ 92%] Built target geos_c
[ 92%] Built target openspace-module-exoplanets
[ 92%] Built target openspace-module-server
[ 93%] Built target openspace-module-globebrowsing
[ 93%] Built target openspace-module-video
[ 94%] Built target openspace-ui-launcher
[ 94%] Built target OpenSpace
[ 98%] Built target codegentest
[100%] Built target OpenSpaceTest
root@b384e20c7345:/OpenSpace#
```

**Comment by curiousercreative** [comment]
@alexanderbock thanks for your attention on this and pointing me toward the docker repo. I believe the initial error I was seeing about CMake files needing to be removed was a result of the source having changed. For context, I built from source a month or two ago following [instructions here](https://docs.openspaceproject.com/en/latest/dev/compiling/ubuntu.html). I'm now attempting to build again after pulling in upstream changes. Initially I received errors suggesting to remove the CMake files as indicated in this PR, but then I found I was still unable to successfully build. I've since succesfully completed a build with the docker image you linked to, but I'm unable to with this [ubuntu default one](https://github.com/OpenSpace/docker/blob/master/build/ubuntu-2204-default.Dockerfile) (which more accurately represents my system). So there may be two build issues I've encountered:
1. Running successive builds after source changes may require cleaning
2. The Ubuntu default build does not appear to be succeeding

**Comment by curiousercreative** [comment]
It seems that gcc 11 and 12 both err while gcc 13 seems ok. [Suspicious commit](https://github.com/OpenSpace/codegen/commit/8798d8a462d93dd5a2fd3b8dfa8917083e50a6ee)
```
OpenSpace/support/coding/codegen/lib/snippets.cpp:28:10: fatal error: format: No such file or directory
   28 | #include <format>
      |          ^~~~~~~~
compilation terminated.
make[2]: *** [support/coding/codegen/lib/CMakeFiles/codegen-lib.dir/build.make:104: support/coding/codegen/lib/CMakeFiles/codegen-lib.dir/snippets.cpp.o] Error 1
```

**Comment by alexanderbock** [comment]
Ah.. Yea, as of about 2 weeks ago, we upped our compile requirements, but I haven't had time to change the docs page accordingly.  Since Ubuntu 24.04 is expected to ship with GCC13, we updated it to: MSVC 19.39, GCC 13, and Clang 17 as a minimum

**Comment by curiousercreative** [comment]
@alexanderbock I've repurposed this PR for instructions on how to install gcc-13 on Ubuntu 22.04.

**Review by alexanderbock — APPROVED** [review]
Sweet!!  Big thanks!

**Pull request merged**
